### ISSUE TITLE
[Deployment] Host the game

### ISSUE THREAD

**Issue by shubhansu-kr** [arujjval/tic-tac-toe#1]
We need to host the game and add the live link to the Readme and repo description.

**Comment by swarupn17** [comment]
Hello @shubhansu-kr !
Please can you assign this task to me i can do this .
Thanks.

**Comment by swarupn17** [comment]
Also please can you add hacktoberfest tag to it.

**Comment by arujjval** [comment]
@swarupn17 @shubhansu-kr website is already been deployed on github pages.
