### ISSUE TITLE
Add Score Option for Tic-Tac-Toe Game

### ISSUE THREAD

**Issue by pulkitgarg04** [arujjval/tic-tac-toe#13]
Hi @arujjval, Currently, the game allows players to play individual rounds, but there is no scoring system to track multiple rounds between the same players.

I can work on this issue, kindly assign me this issue.

**Comment by arujjval** [comment]
Good suggestion. You can start with this.

**Comment by ANUKOOL324** [comment]
I had already done the scoreboard Feature ! fix issue #20

**Comment by Pranav014** [comment]
I dont see any scoring, if the issue is still open, I would like to be assigned this
