### ISSUE TITLE
Display Current Player in Tic-Tac-Toe Game

### ISSUE THREAD

**Issue by pulkitgarg04** [arujjval/tic-tac-toe#14]
Hi @arujjval, Players in the game may have to keep track of whose turn it is manually. To improve the user experience, we can add a feature that clearly displays which player's turn it is (Player X or Player O) during the game.

I can work on this issue, please assign me this issue.

**Comment by lightning-sagar** [comment]
hey i have done it and make a pr too..., can u assign me please..., and check the pr also....
