### ISSUE TITLE
Feature: Add Sound Effects to Game Actions

### ISSUE THREAD

**Issue by masabinhok** [arujjval/tic-tac-toe#19]
### Feature: Add Sound Effects to Game Actions

**Description:**
We want to enhance the user experience of the Tic Tac Toe game by adding sound effects for key game actions such as placing a marker, winning, and resetting the game. Adding sound will make the game more interactive and fun.

**Proposed Solution:**
1. **Move Sound (Click)**: 
   - Play a sound when a player places a marker (X or O) on the board.
   
2. **Win Sound**:
   - Play a celebratory sound when a player wins the game.

3. **Reset Sound**:
   - Play a sound when the game board is reset for a new round.

**Tasks:**
1. Add audio files to the project (`click.mp3`, `win.mp3`, `reset.mp3`).
2. Create an HTML `<audio>` element or use the `Audio` object in JavaScript to handle the sound effects.
3. Trigger the appropriate sound on the following events:
   - **Move**: When a player clicks a cell.
   - **Win**: When the game detects a winning condition.
   - **Reset**: When the game is reset.
4. Ensure all sounds are loaded properly and handle any errors if the sound files fail to load.

**Acceptance Criteria:**
- Sounds play correctly on all major browsers (Chrome, Firefox, Safari, Edge).
- No lag or delay in sound playing during gameplay.
- Optionally, mute or volume control can be added to the game for user control over the sound effects.

**Comment by masabinhok** [comment]
Kindly assign me this issue under hacktoberfest, i would love to work on this.

**Comment by arujjval** [comment]
That sounds great to me. You can start with this.

**Comment by masabinhok** [comment]
Adding sound would of course sound good… haha, jk. I submitted a PR for this (#25). Now your game can finally make some noise!
