### ISSUE TITLE
Hosting the website

### ISSUE THREAD

**Issue by Jay-1409** [arujjval/tic-tac-toe#2]
I want to help you with hosting this website.
Please assign this to me under hacktoberfest 2024

**Comment by arujjval** [comment]
Sure. Use github pages to host it.

**Comment by Jay-1409** [comment]
Hey i did it after forking it: 
https://jay-1409.github.io/tic-tac-toe/ 
Can you check it out?. 
This i hosted in github pages since that is why I has my username. would you like me to host it in vercel ?

**Comment by Jay-1409** [comment]
please merge the pr, thanks!!

**Comment by arujjval** [comment]
@Jay-1409 I think vercel would be an overkill. I will close your issue with hacktoberfest-accepted tag. And thanks for your interest in this issue.
