### ISSUE TITLE
[feat] There is background image 

### ISSUE THREAD

**Issue by rsr077** [arujjval/tic-tac-toe#22]
Background image problem player confuse in 0s can You change relative image 
than look like good .

Desktop 

<img width="960" alt="Tik-tok " src="https://github.com/user-attachments/assets/c292ad88-da24-40bc-aa45-c154f3f1dd2a">

Phone 

![WhatsApp Image 2024-10-04 at 7 06 35 AM](https://github.com/user-attachments/assets/2ff318fe-88a5-4abe-9766-e76a092886ce)

**Comment by ShivRaiGithub** [comment]
I can work on it. Please assign it to me and add the respective labels. Thank you.

**Comment by arujjval** [comment]
Okay. you can start.

**Comment by Er-luffy-D** [comment]
@arujjval ,Can you assign this issue to me if it is still open....

**Comment by arujjval** [comment]
@rsr077 are you still working?

**Comment by Er-luffy-D** [comment]
can i start working on it @arujjval ? and is it ok to change the current background....

**Comment by arujjval** [comment]
@Er-luffy-D you can try if you want.

**Comment by Er-luffy-D** [comment]
> @Er-luffy-D you can try if you want.

@arujjval ok
