### ISSUE TITLE
[UI Enhancement / Feature]Add confetti after a winning condition gets true.

### ISSUE THREAD

**Issue by preranah7** [arujjval/tic-tac-toe#23]
Adding a confetti blast after a winning condition gets true would be enhancement in user experience 
Solution-
A cdn link of confetti-canvas or npm package(confetti-canvas) can be added and javascript/nodejs function can be named as triggeredConfetti() can be implemented.
Please assign it to me if you find it worth UI Enhancing.
Thankyou.

**Comment by arujjval** [comment]
Sure. You can try this.
