### ISSUE TITLE
Make tic-tac-toe UI better

### ISSUE THREAD

**Issue by arujjval** [arujjval/tic-tac-toe#3]
For now, the UI for the actual game does not look great. Use CSS styling to make it better looking.
 
Suggestions: 
Add little animations

**Comment by Ooze-Man** [comment]
I have a PR out for this issue. Can you please assign to me?

**Comment by arujjval** [comment]
Sure. 
Are you done with your PR?

**Comment by Ooze-Man** [comment]
Yes, but now it looks like there are some conflicts that need resolved. Ill do that ASAP.

**Comment by Ooze-Man** [comment]
@arujjval fixed merge conflicts by combining the latest updates from other PRs with mine. Checked for issues after making the changes and everything works and looks great. PR is ready for approval.

**Comment by arujjval** [comment]
Okay, mention the PR here

**Comment by Ooze-Man** [comment]
Feature/UI-and-functional-updates #6

**Comment by Lakshita-Kumawat** [comment]
@arujjval can i also help in the ui? There many things left to add in the website

**Comment by Ooze-Man** [comment]
@arujjval you didn't merge my PR.. but you marked this as complete. Was there an issue with the code?
