### ISSUE TITLE
FIX DOCUMENTATION, Contributing.md file has one important missing command to stage the changes made in files.

### ISSUE THREAD

**Issue by preranah7** [arujjval/tic-tac-toe#33]
As I was working on an issue, I wanted to make a pull request for the changes and the solution I implemented.
While following the contributing.md file it gave me a error saying your changes are not staged when the git commit -m command was executed.
The git add command is necessary to stage changes before committing them. 
Without this step, the changes will not be included in the commit. 
The command git add . stages all changes, or documentation will provide specific command to stage/add a specific file.
Including the git add command makes the documentation more accurate and ensures that users and most specifically the new comers follow the correct Git workflow when committing changes. 
Thankyou.

**Comment by arujjval** [comment]
That's the obvious part. A contributor should go through the basics of Git and GitHub before contributing.
