### ISSUE TITLE
New feature Request-Customizable Themes

### ISSUE THREAD

**Issue by pragna7** [arujjval/tic-tac-toe#36]
major feature change: 
Allow users to change the background, colors based on predefined themes or their choice.
Provide a dark mode option.

benefits-
1. Improved  User Experience:
Visual Appeal: Customizable themes provide players with a choice of aesthetic options, allowing them to switch between light, dark, and neon themes. This variety in appearance enhances user satisfaction as they can choose the look that best fits their preference or mood.
2. Accessibility and Comfort:
Reduced Eye Strain (Dark Theme): The dark theme can be especially beneficial for users playing the game in low-light environments. It reduces eye strain and improves readability in dim settings.
High-Contrast (Neon Theme): The neon theme offers high contrast, which can be useful for users with visual impairments or those who prefer bold and vibrant visuals for better clarity.
Adaptability: Users can choose the theme that best suits their environment, whether it’s a bright setting (light theme) or a dark one (dark theme), providing comfort and accessibility for a broader audience.

**Comment by pragna7** [comment]
@arujjval Can you please assign me this task under hactoberfest ?

**Comment by arujjval** [comment]
The look is already dark-themed. I don't think we need this feature.
