### ISSUE TITLE
New Feature-Dynamic Board Size Adjustment

### ISSUE THREAD

**Issue by pragna7** [arujjval/tic-tac-toe#41]
Allow players to customize the size of the board (e.g., 3x3, 4x4, 5x5) before starting the game.
Benefits:
Offers more flexibility and different levels of difficulty.
A larger board can add more strategic depth and extend gameplay time.

**Comment by pragna7** [comment]
this feature makes the game more interesting and fun by which players  extend gameplay time, can you assign this issue to me under hacktoberfest?

**Comment by Pranav014** [comment]
@pragna7 Can you assign this to me with hacktoberfest tag

**Comment by arujjval** [comment]
Tic-tac-toe has pretty standard rules. I don't think this is necessary.
